### ISSUE TITLE
JSON::ParserError unexpected token

### ISSUE THREAD

**Issue by xbits** [d4be4st/mina-data_sync#7]
Hi! Getting this error when I try to sync. Is this a bug in the gem or something wrong with my systems?
```
$ mina staging data_sync:pull
-----> Loading rbenv
-----> Dumping database
       /home/XXX/.rbenv/versions/2.4.0/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at 'I, [2018-08-29T14:06:16.352189 #27910]  INFO -- sentry: ** [Raven] Raven 2.6.2 ready to catch errors (JSON::ParserError)
       {"adapter":"postgresql","encoding":"unicode","host":"localhost","pool":20,"database":"XXX_production","username":"appuser","password":"XXX","port":5432}'
       	from /home/XXX/.rbenv/versions/2.4.0/lib/ruby/2.4.0/json/common.rb:156:in `parse'
       	from -e:2:in `<main>'
-----> 
       /home/XXX/.rbenv/versions/2.4.0/lib/ruby/2.4.0/json/common.rb:156:in `parse': 743: unexpected token at 'I, [2018-08-29T14:06:16.352189 #27910]  INFO -- sentry: ** [Raven] Raven 2.6.2 ready to catch errors (JSON::ParserError)
       {"adapter":"postgresql","encoding":"unicode","host":"localhost","pool":20,"database":"XXX_production","username":"appuser","password":"XXX","port":5432}'
       	from /home/XXX/.rbenv/versions/2.4.0/lib/ruby/2.4.0/json/common.rb:156:in `parse'
       	from -e:2:in `<main>'
       Connection to 178.32.215.123 closed.

       Elapsed time: 13.41 seconds
-----> Copying backup
-----> Backup: tmp/XXX-production-2018-08-29.sql
       rsync: link_stat "/var/www/XXX/current/tmp/XXX-production-2018-08-29.sql" failed: No such file or directory (2)

       rsync error: some files/attrs were not transferred (see previous errors) (code 23) at main.c(1655) [Receiver=3.1.1]

       rsync: [Receiver] write error: Broken pipe (32)

 !     Run Error`
```

**Comment by me-kirill** [comment]
@xbits Hi! You should remove 

> I, [2018-08-29T14:06:16.352189 #27910]  INFO -- sentry: ** [Raven] Raven 2.6.2 ready to catch errors (JSON::ParserError)

 this from your app's STDOUT.
